/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import implementaciones.ClientesDAO;
import interfaces.IClientesDAO;
import interfaces.IDireccionesDAO;
import java.util.logging.Logger;

/**
 *
 * @author lv1013
 */
public class FrmAyuda extends javax.swing.JFrame {
private static final Logger LOG = Logger.getLogger(ClientesDAO.class.getName());
    public final IClientesDAO clientesDAO;
    public final IDireccionesDAO direccionesDAO;
    
    public FrmAyuda(IClientesDAO clientesDAO,IDireccionesDAO direccionesDAO) {
        this.clientesDAO=clientesDAO;
        this.direccionesDAO=direccionesDAO;
        initComponents();
        this.setSize(400, 215);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblAyuda = new javax.swing.JLabel();
        lblContactar = new javax.swing.JLabel();
        lblRecuperarContra = new javax.swing.JLabel();
        btnDesconectar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(12, 28, 68));
        jPanel1.setForeground(new java.awt.Color(12, 28, 68));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAyuda.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 50)); // NOI18N
        lblAyuda.setForeground(new java.awt.Color(255, 255, 255));
        lblAyuda.setText("Ayuda");
        jPanel1.add(lblAyuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        lblContactar.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        lblContactar.setForeground(new java.awt.Color(255, 255, 255));
        lblContactar.setText("Contactar con la sucursal");
        lblContactar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblContactarMouseClicked(evt);
            }
        });
        jPanel1.add(lblContactar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        lblRecuperarContra.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        lblRecuperarContra.setForeground(new java.awt.Color(255, 255, 255));
        lblRecuperarContra.setText("Recuperar contraseña");
        jPanel1.add(lblRecuperarContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        btnDesconectar.setBackground(new java.awt.Color(183, 210, 242));
        btnDesconectar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnDesconectar.setText("Volver");
        btnDesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesconectarActionPerformed(evt);
            }
        });
        jPanel1.add(btnDesconectar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblContactarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblContactarMouseClicked

    }//GEN-LAST:event_lblContactarMouseClicked

    private void btnDesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesconectarActionPerformed
        FrmLogin frmLogin = new FrmLogin(clientesDAO,direccionesDAO);
        this.setVisible(false);
        frmLogin.setVisible(true);
    }//GEN-LAST:event_btnDesconectarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDesconectar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAyuda;
    private javax.swing.JLabel lblContactar;
    private javax.swing.JLabel lblRecuperarContra;
    // End of variables declaration//GEN-END:variables
}
