/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import implementaciones.ClientesDAO;
import interfaces.IClientesDAO;
import interfaces.IDireccionesDAO;
import java.util.logging.Logger;

/**
 *
 * @author lv1013
 */
public class FrmCambiarCuenta extends javax.swing.JFrame {
private static final Logger LOG = Logger.getLogger(ClientesDAO.class.getName());
    public final IClientesDAO clientesDAO;
    public final IDireccionesDAO direccionesDAO;
    /**
    * Método constructor que inicializa los atributos al valor de sus parámetros.
    * @param clientesDAO clientesDAO.
    * @param direccionesDAO direccionesDAO.
    */
    public FrmCambiarCuenta(IClientesDAO clientesDAO,IDireccionesDAO direccionesDAO) {
        this.clientesDAO=clientesDAO;
        this.direccionesDAO=direccionesDAO;
        initComponents();
        this.setSize(450, 250);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblCambiarCuenta = new javax.swing.JLabel();
        lblSeleccionarCuenta = new javax.swing.JLabel();
        btnRegresar1 = new javax.swing.JButton();
        cbxCuentas = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(12, 28, 68));
        jPanel1.setForeground(new java.awt.Color(12, 28, 68));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCambiarCuenta.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 50)); // NOI18N
        lblCambiarCuenta.setForeground(new java.awt.Color(255, 255, 255));
        lblCambiarCuenta.setText("Cambiar cuenta");
        jPanel1.add(lblCambiarCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        lblSeleccionarCuenta.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        lblSeleccionarCuenta.setForeground(new java.awt.Color(255, 255, 255));
        lblSeleccionarCuenta.setText("Seleccione una cuenta");
        jPanel1.add(lblSeleccionarCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        btnRegresar1.setBackground(new java.awt.Color(183, 210, 242));
        btnRegresar1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnRegresar1.setText("Regresar");
        btnRegresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresar1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        cbxCuentas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbxCuentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 350, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresar1ActionPerformed
        FrmMenu frmMenu = new FrmMenu(clientesDAO,direccionesDAO);
        this.setVisible(false);
        frmMenu.setVisible(true);
    }//GEN-LAST:event_btnRegresar1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar1;
    private javax.swing.JComboBox<String> cbxCuentas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCambiarCuenta;
    private javax.swing.JLabel lblSeleccionarCuenta;
    // End of variables declaration//GEN-END:variables
}
