/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import implementaciones.ClientesDAO;
import interfaces.IClientesDAO;
import interfaces.IDireccionesDAO;
import java.util.logging.Logger;

/**
 *
 * @author lv1013
 */
public class FrmCancelarCuenta extends javax.swing.JFrame {
private static final Logger LOG = Logger.getLogger(ClientesDAO.class.getName());
    public final IClientesDAO clientesDAO;
    public final IDireccionesDAO direccionesDAO;
    /**
    * Método constructor que inicializa los atributos al valor de sus parámetros.
    * @param clientesDAO clientesDAO.
    * @param direccionesDAO direccionesDAO.
    */
    public FrmCancelarCuenta(IClientesDAO clientesDAO,IDireccionesDAO direccionesDAO) {
        this.clientesDAO=clientesDAO;
        this.direccionesDAO=direccionesDAO;
        initComponents();
        this.setSize(500, 330);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblCancelarCuenta = new javax.swing.JLabel();
        txtContrasena = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        lblContrasena = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(12, 28, 68));
        jPanel1.setForeground(new java.awt.Color(12, 28, 68));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCancelarCuenta.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 50)); // NOI18N
        lblCancelarCuenta.setForeground(new java.awt.Color(255, 255, 255));
        lblCancelarCuenta.setText("Cancelar Cuenta");
        jPanel1.add(lblCancelarCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));
        jPanel1.add(txtContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 350, 50));

        btnAceptar.setBackground(new java.awt.Color(65, 103, 158));
        btnAceptar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnAceptar.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 90, 40));

        lblContrasena.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        lblContrasena.setForeground(new java.awt.Color(255, 255, 255));
        lblContrasena.setText("Contraseña");
        jPanel1.add(lblContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        btnRegresar.setBackground(new java.awt.Color(183, 210, 242));
        btnRegresar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
      FrmMenu frmMenu = new FrmMenu(clientesDAO,direccionesDAO);
      this.setVisible(false);
      frmMenu.setVisible(true);
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
          FrmMenu frmMenu = new FrmMenu(clientesDAO,direccionesDAO);
       this.setVisible(false);
       frmMenu.setVisible(true);
    }//GEN-LAST:event_btnRegresarActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCancelarCuenta;
    private javax.swing.JLabel lblContrasena;
    private javax.swing.JTextField txtContrasena;
    // End of variables declaration//GEN-END:variables
}
