

package UI;

import implementaciones.ClientesDAO;
import interfaces.IClientesDAO;
import interfaces.IDireccionesDAO;
import java.util.logging.Logger;

/**
 *
 * @author lv1013
 */
public class FrmModificarDatos extends javax.swing.JFrame {
private static final Logger LOG = Logger.getLogger(ClientesDAO.class.getName());
    public final IClientesDAO clientesDAO;
    public final IDireccionesDAO direccionesDAO;
    /**
    * Método constructor que inicializa los atributos al valor de sus parámetros.
    * @param clientesDAO clientesDAO.
    * @param direccionesDAO direccionesDAO.
    */
    public FrmModificarDatos(IClientesDAO clientesDAO,IDireccionesDAO direccionesDAO) {
        this.clientesDAO=clientesDAO;
        this.direccionesDAO=direccionesDAO;
        initComponents();
        this.setSize(650, 480);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblModificarDatos = new javax.swing.JLabel();
        lblCambiarContrasena = new javax.swing.JLabel();
        txtApellidoMaterno = new javax.swing.JTextField();
        txtColonia = new javax.swing.JTextField();
        lblApellidoMaterno_ = new javax.swing.JLabel();
        lblColonia = new javax.swing.JLabel();
        lblApellidoPaterno_ = new javax.swing.JLabel();
        txtApellidoPaterno = new javax.swing.JTextField();
        lblApellidoPaterno = new javax.swing.JLabel();
        lblApellidoMaterno = new javax.swing.JLabel();
        lblInformacionPersonal1 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblCalle = new javax.swing.JLabel();
        txtCalle = new javax.swing.JTextField();
        lblNumero = new javax.swing.JLabel();
        txtContrasena = new javax.swing.JTextField();
        lblNombre1 = new javax.swing.JLabel();
        calendarPanel1 = new com.github.lgooddatepicker.components.CalendarPanel();
        lblDomicilio1 = new javax.swing.JLabel();
        txtNumero1 = new javax.swing.JTextField();
        btnRegresar1 = new javax.swing.JButton();
        btnIniciarSesion1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(12, 28, 68));
        jPanel1.setForeground(new java.awt.Color(12, 28, 68));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblModificarDatos.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 50)); // NOI18N
        lblModificarDatos.setForeground(new java.awt.Color(255, 255, 255));
        lblModificarDatos.setText("Modificar datos");
        jPanel1.add(lblModificarDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        lblCambiarContrasena.setText("Cambiar Contraseña");
        lblCambiarContrasena.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        lblCambiarContrasena.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lblCambiarContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, -1, -1));
        jPanel1.add(txtApellidoMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 270, 40));

        txtColonia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtColoniaKeyTyped(evt);
            }
        });
        jPanel1.add(txtColonia, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 270, 30));

        lblApellidoMaterno_.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        lblApellidoMaterno_.setForeground(new java.awt.Color(255, 255, 255));
        lblApellidoMaterno_.setText("Materno");
        jPanel1.add(lblApellidoMaterno_, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 60, -1));

        lblColonia.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        lblColonia.setForeground(new java.awt.Color(255, 255, 255));
        lblColonia.setText("Colonia");
        jPanel1.add(lblColonia, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        lblApellidoPaterno_.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        lblApellidoPaterno_.setForeground(new java.awt.Color(255, 255, 255));
        lblApellidoPaterno_.setText("Paterno");
        jPanel1.add(lblApellidoPaterno_, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 60, -1));
        jPanel1.add(txtApellidoPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 270, 40));

        lblApellidoPaterno.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        lblApellidoPaterno.setForeground(new java.awt.Color(255, 255, 255));
        lblApellidoPaterno.setText("Apellido");
        jPanel1.add(lblApellidoPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 60, -1));

        lblApellidoMaterno.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        lblApellidoMaterno.setForeground(new java.awt.Color(255, 255, 255));
        lblApellidoMaterno.setText("Apellido");
        jPanel1.add(lblApellidoMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 60, -1));

        lblInformacionPersonal1.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        lblInformacionPersonal1.setForeground(new java.awt.Color(255, 255, 255));
        lblInformacionPersonal1.setText("Información personal");
        jPanel1.add(lblInformacionPersonal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        lblNombre.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setText("Fecha de nacimiento");
        jPanel1.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, -1, -1));

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 270, 30));

        lblCalle.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        lblCalle.setForeground(new java.awt.Color(255, 255, 255));
        lblCalle.setText("Calle");
        jPanel1.add(lblCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        txtCalle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCalleKeyTyped(evt);
            }
        });
        jPanel1.add(txtCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 270, 30));

        lblNumero.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        lblNumero.setForeground(new java.awt.Color(255, 255, 255));
        lblNumero.setText("Número");
        jPanel1.add(lblNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        txtContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContrasenaActionPerformed(evt);
            }
        });
        txtContrasena.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtContrasenaKeyTyped(evt);
            }
        });
        jPanel1.add(txtContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, 240, 30));

        lblNombre1.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        lblNombre1.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre1.setText("Nombre");
        jPanel1.add(lblNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));
        jPanel1.add(calendarPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 290, 190));

        lblDomicilio1.setText("Domicilio");
        lblDomicilio1.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        lblDomicilio1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lblDomicilio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        txtNumero1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumero1KeyTyped(evt);
            }
        });
        jPanel1.add(txtNumero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 270, 30));

        btnRegresar1.setBackground(new java.awt.Color(183, 210, 242));
        btnRegresar1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnRegresar1.setText("Regresar");
        btnRegresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresar1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));

        btnIniciarSesion1.setText("Guardar cambios");
        btnIniciarSesion1.setBackground(new java.awt.Color(65, 103, 158));
        btnIniciarSesion1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnIniciarSesion1.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciarSesion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesion1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnIniciarSesion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 380, 170, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 709, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtColoniaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtColoniaKeyTyped
        if (evt.getKeyChar() >= 32 && evt.getKeyChar() <= 64 || evt.getKeyChar() >= 91 && evt.getKeyChar() <= 96 || evt.getKeyChar() >= 123 && evt.getKeyChar() <= 208 || evt.getKeyChar() >= 210 && evt.getKeyChar() <= 240 || evt.getKeyChar() >= 242 && evt.getKeyChar() <= 255) {
            evt.consume();
        }
    }//GEN-LAST:event_txtColoniaKeyTyped

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtCalleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCalleKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCalleKeyTyped

    private void txtContrasenaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContrasenaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContrasenaKeyTyped

    private void txtNumero1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumero1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumero1KeyTyped

    private void txtContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContrasenaActionPerformed

    private void btnRegresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresar1ActionPerformed
       FrmMenu frmMenu = new FrmMenu(clientesDAO,direccionesDAO);
       this.setVisible(false);
       frmMenu.setVisible(true);
    }//GEN-LAST:event_btnRegresar1ActionPerformed

    private void btnIniciarSesion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIniciarSesion1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarSesion1;
    private javax.swing.JButton btnRegresar1;
    private com.github.lgooddatepicker.components.CalendarPanel calendarPanel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblApellidoMaterno;
    private javax.swing.JLabel lblApellidoMaterno_;
    private javax.swing.JLabel lblApellidoPaterno;
    private javax.swing.JLabel lblApellidoPaterno_;
    private javax.swing.JLabel lblCalle;
    private javax.swing.JLabel lblCambiarContrasena;
    private javax.swing.JLabel lblColonia;
    private javax.swing.JLabel lblDomicilio1;
    private javax.swing.JLabel lblInformacionPersonal1;
    private javax.swing.JLabel lblModificarDatos;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JTextField txtApellidoMaterno;
    private javax.swing.JTextField txtApellidoPaterno;
    private javax.swing.JTextField txtCalle;
    private javax.swing.JTextField txtColonia;
    private javax.swing.JTextField txtContrasena;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumero1;
    // End of variables declaration//GEN-END:variables
}
