/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import implementaciones.ClientesDAO;
import interfaces.IClientesDAO;
import interfaces.IDireccionesDAO;
import java.util.logging.Logger;

/**
 *
 * @author lv1013
 */
public class FrmMenu extends javax.swing.JFrame {
private static final Logger LOG = Logger.getLogger(ClientesDAO.class.getName());
    public final IClientesDAO clientesDAO;
    public final IDireccionesDAO direccionesDAO;
   /**
    * Método constructor que inicializa los atributos al valor de sus parámetros.
    * @param clientesDAO clientesDAO.
    * @param direccionesDAO direccionesDAO.
    */
    public FrmMenu(IClientesDAO clientesDAO,IDireccionesDAO direccionesDAO) {
        this.clientesDAO=clientesDAO;
        this.direccionesDAO=direccionesDAO;
        initComponents();
        this.setSize(450, 400);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAyuda = new javax.swing.JButton();
        btnTransferir = new javax.swing.JButton();
        btnRetirar = new javax.swing.JButton();
        btnModificarDatos = new javax.swing.JButton();
        btnVerOperaciones = new javax.swing.JButton();
        btnCambiarCuenta = new javax.swing.JButton();
        btnCancelarCuenta1 = new javax.swing.JButton();
        btnDesconectar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblDinero = new javax.swing.JLabel();
        lblSaldoDisponible = new javax.swing.JLabel();
        lblMenu1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(12, 28, 68));
        jPanel1.setForeground(new java.awt.Color(12, 28, 68));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAyuda.setBackground(new java.awt.Color(183, 210, 242));
        btnAyuda.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnAyuda.setText("Ayuda");
        jPanel1.add(btnAyuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, -1, -1));

        btnTransferir.setBackground(new java.awt.Color(65, 103, 158));
        btnTransferir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnTransferir.setForeground(new java.awt.Color(255, 255, 255));
        btnTransferir.setText("Transferir");
        btnTransferir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransferirActionPerformed(evt);
            }
        });
        jPanel1.add(btnTransferir, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 120, -1));

        btnRetirar.setBackground(new java.awt.Color(65, 103, 158));
        btnRetirar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnRetirar.setForeground(new java.awt.Color(255, 255, 255));
        btnRetirar.setText("Retirar");
        btnRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRetirar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 120, -1));

        btnModificarDatos.setBackground(new java.awt.Color(65, 103, 158));
        btnModificarDatos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnModificarDatos.setForeground(new java.awt.Color(255, 255, 255));
        btnModificarDatos.setText("Modificar datos");
        btnModificarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarDatosActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificarDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 120, -1));

        btnVerOperaciones.setBackground(new java.awt.Color(65, 103, 158));
        btnVerOperaciones.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnVerOperaciones.setForeground(new java.awt.Color(255, 255, 255));
        btnVerOperaciones.setText("Ver operaciones");
        btnVerOperaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerOperacionesActionPerformed(evt);
            }
        });
        jPanel1.add(btnVerOperaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 120, -1));

        btnCambiarCuenta.setBackground(new java.awt.Color(65, 103, 158));
        btnCambiarCuenta.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnCambiarCuenta.setForeground(new java.awt.Color(255, 255, 255));
        btnCambiarCuenta.setText("Cambiar cuenta");
        btnCambiarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarCuentaActionPerformed(evt);
            }
        });
        jPanel1.add(btnCambiarCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 120, -1));

        btnCancelarCuenta1.setBackground(new java.awt.Color(65, 103, 158));
        btnCancelarCuenta1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnCancelarCuenta1.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelarCuenta1.setText("Cancelar cuenta");
        btnCancelarCuenta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarCuenta1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelarCuenta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 120, -1));

        btnDesconectar.setBackground(new java.awt.Color(183, 210, 242));
        btnDesconectar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnDesconectar.setText("Desconectar");
        btnDesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesconectarActionPerformed(evt);
            }
        });
        jPanel1.add(btnDesconectar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        jPanel2.setBackground(new java.awt.Color(65, 103, 158));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDinero.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 36)); // NOI18N
        lblDinero.setForeground(new java.awt.Color(255, 255, 255));
        lblDinero.setText("----------");
        jPanel2.add(lblDinero, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 170, -1));

        lblSaldoDisponible.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        lblSaldoDisponible.setForeground(new java.awt.Color(255, 255, 255));
        lblSaldoDisponible.setText("Saldo disponible");
        jPanel2.add(lblSaldoDisponible, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 190, 110));

        lblMenu1.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 50)); // NOI18N
        lblMenu1.setForeground(new java.awt.Color(255, 255, 255));
        lblMenu1.setText("Menú");
        jPanel1.add(lblMenu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTransferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransferirActionPerformed
        FrmTransferencia frmTransferencia = new FrmTransferencia(clientesDAO,direccionesDAO);
        this.setVisible(false);
        frmTransferencia.setVisible(true);
    }//GEN-LAST:event_btnTransferirActionPerformed

    private void btnCancelarCuenta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarCuenta1ActionPerformed
       FrmCancelarCuenta frmCancelarCuenta = new FrmCancelarCuenta(clientesDAO,direccionesDAO);
       this.setVisible(false);
       frmCancelarCuenta.setVisible(true);
    }//GEN-LAST:event_btnCancelarCuenta1ActionPerformed

    private void btnModificarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarDatosActionPerformed
      FrmModificarDatos frmModificarDatos = new FrmModificarDatos(clientesDAO,direccionesDAO);
      this.setVisible(false);
      frmModificarDatos.setVisible(true);
    }//GEN-LAST:event_btnModificarDatosActionPerformed

    private void btnVerOperacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerOperacionesActionPerformed
        FrmVerOperaciones frmVerOperaciones = new FrmVerOperaciones(clientesDAO,direccionesDAO);
        this.setVisible(false);
        frmVerOperaciones.setVisible(true);
    }//GEN-LAST:event_btnVerOperacionesActionPerformed

    private void btnCambiarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarCuentaActionPerformed
      FrmCambiarCuenta frmCambiarCuenta = new FrmCambiarCuenta(clientesDAO,direccionesDAO);
      this.setVisible(false);
      frmCambiarCuenta.setVisible(true);
    }//GEN-LAST:event_btnCambiarCuentaActionPerformed

    private void btnRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirarActionPerformed
        FrmRetirar frmRetirar = new FrmRetirar(clientesDAO,direccionesDAO);
        this.setVisible(false);
        frmRetirar.setVisible(true);
    }//GEN-LAST:event_btnRetirarActionPerformed

    private void btnDesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesconectarActionPerformed
       FrmLogin frmLogin = new FrmLogin(clientesDAO,direccionesDAO);
       this.setVisible(false);
       frmLogin.setVisible(true);
    }//GEN-LAST:event_btnDesconectarActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAyuda;
    private javax.swing.JButton btnCambiarCuenta;
    private javax.swing.JButton btnCancelarCuenta1;
    private javax.swing.JButton btnDesconectar;
    private javax.swing.JButton btnModificarDatos;
    private javax.swing.JButton btnRetirar;
    private javax.swing.JButton btnTransferir;
    private javax.swing.JButton btnVerOperaciones;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblDinero;
    private javax.swing.JLabel lblMenu1;
    private javax.swing.JLabel lblSaldoDisponible;
    // End of variables declaration//GEN-END:variables
}
