/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;
import implementaciones.ClientesDAO;
import interfaces.IClientesDAO;
import interfaces.IDireccionesDAO;
import java.util.logging.Logger;

/**
 *
 * @author lv1013
 */
public class FrmRetirar extends javax.swing.JFrame {
private static final Logger LOG = Logger.getLogger(ClientesDAO.class.getName());
    public final IClientesDAO clientesDAO;
    public final IDireccionesDAO direccionesDAO;
    /**
    * Método constructor que inicializa los atributos al valor de sus parámetros.
    * @param clientesDAO clientesDAO.
    * @param direccionesDAO direccionesDAO.
    */
    public FrmRetirar(IClientesDAO clientesDAO,IDireccionesDAO direccionesDAO) {
        this.clientesDAO=clientesDAO;
        this.direccionesDAO=direccionesDAO;
        initComponents();
        this.setSize(350, 300);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblRetirar = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        lblGenerarContrasena = new javax.swing.JButton();
        lblGenerarFolio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(12, 28, 68));
        jPanel1.setForeground(new java.awt.Color(12, 28, 68));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRetirar.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 50)); // NOI18N
        lblRetirar.setForeground(new java.awt.Color(255, 255, 255));
        lblRetirar.setText("Retirar");
        jPanel1.add(lblRetirar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        btnRegresar.setBackground(new java.awt.Color(183, 210, 242));
        btnRegresar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        lblGenerarContrasena.setBackground(new java.awt.Color(65, 103, 158));
        lblGenerarContrasena.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblGenerarContrasena.setForeground(new java.awt.Color(255, 255, 255));
        lblGenerarContrasena.setText("Generar contraseña");
        lblGenerarContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblGenerarContrasenaActionPerformed(evt);
            }
        });
        jPanel1.add(lblGenerarContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 170, 30));

        lblGenerarFolio.setBackground(new java.awt.Color(65, 103, 158));
        lblGenerarFolio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblGenerarFolio.setForeground(new java.awt.Color(255, 255, 255));
        lblGenerarFolio.setText("Generar folio");
        lblGenerarFolio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblGenerarFolioActionPerformed(evt);
            }
        });
        jPanel1.add(lblGenerarFolio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 170, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        FrmMenu frmMenu = new FrmMenu(clientesDAO,direccionesDAO);
        this.setVisible(false);
        frmMenu.setVisible(true);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void lblGenerarContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblGenerarContrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblGenerarContrasenaActionPerformed

    private void lblGenerarFolioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblGenerarFolioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblGenerarFolioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton lblGenerarContrasena;
    private javax.swing.JButton lblGenerarFolio;
    private javax.swing.JLabel lblRetirar;
    // End of variables declaration//GEN-END:variables
}
